/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'lastName ', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string 
  @column()
  declare lastName: string 
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ThemeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = ThemeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string  
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'themeId', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare themeId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
} 

export class MemberSchema extends BaseModel {

  static $columns = ['createdAt', 'id', 'teamId', 'userId', 'updatedAt'] as const
  
  $columns = MemberSchema.$columns
  
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  
  @column({ isPrimary: true })
  declare id: string
  
  @column()
  declare projectId: string
  
  @column()
  declare userId: string
  
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}


export class FiliereSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const

  $columns = FiliereSchema.$columns

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime


  @column({ isPrimary: true })
  declare id: string

  @column()
  declare name: string

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}



export class GradeSchema extends BaseModel {

  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const

  $columns = GradeSchema.$columns

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column({ isPrimary: true })
  declare id: string

  @column()
  declare name: string

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null

}


export class InterestedSchema extends BaseModel {

  static $columns = ['id', 'userId', 'projectId','createdAt', 'updatedAt'] as const

  $columns = InterestedSchema.$columns

  @column({ isPrimary: true })
  declare id: string

  @column()
  declare userId: string

  @column()
  declare projectId: string

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null  

}


export class TeamSchema extends BaseModel {

  static $columns = ['createdAt', 'id', 'name', 'projectId', 'userId', 'updatedAt'] as const

  $columns = TeamSchema.$columns

  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime

  @column({ isPrimary: true })
  declare id: string

  @column()
  declare name: string

  @column()
  declare projectId: string

  @column()
  declare userId: string

  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null

}

  

  
  
